### ISSUE TITLE
Note Splashes for Keys 7 to 9 are bugged.

### ISSUE THREAD

**Issue by Tattleamelia** [FunkinExtraKeys/FNF-PsychEngine-EK#17] opened 2024-08-07 04:10 UTC
### Describe your bug here.

Simply put, the Rombus, Left 2, Down 2, Up 2 and Right 2 keys all have bugged Note Splashes, either not showing up at all or briefly showing the first frame of the specific Note Splashes' XML.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is completely the base EK.

**Comment by tposejank** [comment] 2024-08-07 04:19
Able to reproduce this, quite don't yet know why this happens

**Comment by tposejank** [comment] 2024-08-07 05:36
b14db0e83eaa93723a5c66965268cc8566bda079 has a bandaid fix, because 8 and 9K are still very offset. But the spawn glitch was fixed.

**Comment by tposejank** [comment] 2024-08-12 23:25
Fixed in commit 775890e3540fe8e3ba88d6679eea68efae6fd4e4

**Closed by tposejank** 2024-08-12 23:25 UTC
Labels: bug
